curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/user -d '{"id":"","about":"Miguel","bio":"azsdklkaDJKD","feed":[],"friendLists":[], "email":"asdasd", "firstName":"Miguel", "lastName":"asas"}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/user -d '{"id":"","about":"Miguel","bio":"azsdklkaDJKD","feed":[],"friendLists":[], "email":"asdasd", "firstName":"Miguel", "lastName":"asas"}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/user -d '{"id":"","about":"Miguel","bio":"azsdklkaDJKD","feed":[],"friendLists":[], "email":"asdasd", "firstName":"Miguel", "lastName":"asas"}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/user -d '{"id":"","about":"Miguel","bio":"azsdklkaDJKD","feed":[],"friendLists":[], "email":"asdasd", "firstName":"Miguel", "lastName":"asas"}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/page -d '{"id":"","description":"asasas","name":"Asaas","website":"asasas","likes":0,"feed":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/page -d '{"id":"","description":"asasas","name":"Asaas","website":"asasas","likes":0,"feed":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/page -d '{"id":"","description":"asasas","name":"Asaas","website":"asasas","likes":0,"feed":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/page -d '{"id":"","description":"asasas","name":"Asaas","website":"asasas","likes":0,"feed":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/friendList -d '{"id":"","name":"asas","owner":"u0","members":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/friendList -d '{"id":"","name":"asas","owner":"u1","members":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/friendList -d '{"id":"","name":"asas","owner":"u2","members":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/friendList -d '{"id":"","name":"asas","owner":"u2","members":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/friendList -d '{"id":"","name":"asas","owner":"u3","members":[]}'
curl -v -H "Content-Type: application/json" -X POST http://localhost:5000/friendList -d '{"id":"","name":"asas","owner":"u10","members":[]}'
curl http://localhost:5000/user/u0
curl http://localhost:5000/user/u1
curl http://localhost:5000/user/u2
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u0/friends -d '{"id":"u1"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u1/friends -d '{"id":"u2"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u2/friends -d '{"id":"u1"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u5/friends -d '{"id":"u6"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u0/post -d '{"id":"","createdTime":"12:12:00 12:12:12", "likes":[], "from":"u0", "to":[], "message":"asadadadadad"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u1/post -d '{"id":"","createdTime":"12:12:00 12:12:12", "likes":[], "from":"u1", "to":[], "message":"asadadadadad"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/user/u3/post -d '{"id":"","createdTime":"12:12:00 12:12:12", "likes":[], "from":"u0", "to":[], "message":"asadadadadad"}'
curl -v -H "Content-Type: application/json" -X POST curl http://localhost:5000/post/p0/post -d '{"id":"","createdTime":"12:12:00 12:12:12", "likes":[], "from":"p0", "to":[], "message":"asadadadadad"}'